* About this project, simple-class-browser

This project is an experiment which creates a much simplified version of Newspeak ~Browsing~ class, only for browsing classes and their nested classes.


* Classes developed

* A1_SimpleIDEBrowser

Core class, method ~browseClass: klass~ instantiates a ~ClassMirror~ and asks for class name.


* Errors to report

This shows as 'out' at the end of the page. It shows only after I expand the Tests class in the message. After that, it keeps happening until reload.

Noclass exemplar for method TEST_CONTEXT in class ClassDeclarationMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class ClassHeaderMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class ClassMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class MethodMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class SlotDeclarationMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method yourclass in class ClassMirrorTests MessageNotUnderstood: UndefinedObject evaluate:


* 1. Top Workspace Non-UI: Browse names of 5 top classes + their nested classes

#+name: workspace-browse-as-text
#+begin_example
|
ideBrowser = A1_SimpleIDEBrowser usingPlatform: platform webIDE: ide.
|

ideBrowser browseIDEClasses.

(* browser browseClassToOut: A1_TestSubjects. *)

#+end_example


* 2. Top Workspace UI: Browse one class A1_TestSubject + it's nested classes

#+name: workspace-browse-in-window
#+begin_example smalltalk
|
simpleIDEBrowser = A1_SimpleIDEBrowser usingPlatform: platform webIDE: ide.
classOrClassDeclarationMirror = A1_TestSubjects.
classUI = simpleIDEBrowser ClassUI forClassDefinedBy: classOrClassDeclarationMirror.
ClassSubject = classUI ClassSubject.
ClassModel = classUI ClassModel.

classModelForBrowsedClass = ClassModel forClassDeclarationMirror: (classUI classDeclarationMirror).
|

platform hopscotch core HopscotchWindow 
    openSubject: (ClassSubject onClassModel: classModelForBrowsedClass)   
#+end_example

* Debugging

** Why is link on A1_SimpleIDEBrowser not followed? - it IS followed, but into the same window, so no changes are visible in the UI.

public enclosingClassSubjects ^ <List[ClassSubject]> = (
	(* Browsing>>ClassSubject: Code from here. *)
	| them = List new. c |
	c:: classMirror.
	[c isNil] whileFalse: [them add: (ClassSubject onDeclaration: c). c:: c enclosingClass].
    break.
	^them
)

because 'them' only contains 1 element A1_SimpleIDEBrowser. The link IS FOLLOWED BUT ENTERS THE SAME SUBJECT, WHICH CREATES THE SAME PRESENTER, SO EVERYTHING LOOKS THE SAME BUT IT IS ONE LEVEL DEEPER.


** Adding detail for class browser

