* About this project, simple-class-browser

This project is an experiment which creates a much simplified version of Newspeak ~Browsing~ class, only for browsing classes and their nested classes.


* Classes developed

* A1_SimpleIDEBrowser

Core class, method ~browseClass: klass~ instantiates a ~ClassMirror~ and asks for class name.


* Errors to report

This shows as 'out' at the end of the page. It shows only after I expand the Tests class in the message. After that, it keeps happening until reload.

Noclass exemplar for method TEST_CONTEXT in class ClassDeclarationMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class ClassHeaderMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class ClassMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class MethodMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method TEST_CONTEXT in class SlotDeclarationMirrorTests MessageNotUnderstood: UndefinedObject evaluate:
Noclass exemplar for method yourclass in class ClassMirrorTests MessageNotUnderstood: UndefinedObject evaluate:


* 1. Top Workspace Non-UI: Get classes on level 1

#+name: workspace-browse-as-text
#+begin_example
|
ideBrowser = A1_SimpleIDEBrowser usingPlatform: platform webIDE: ide.
|

ideBrowser browseIDEClasses.

(* browser browseClass: A1_TestSubjects. *)

#+end_example

#+name: workspace-browse-in-window
#+begin_example
|
ideBrowser = A1_SimpleIDEBrowser usingPlatform: platform webIDE: ide.
klass = A1_TestSubjects.
classBrowser = ideBrowser ClassBrowser forClass: klass.
|

platform hopscotch core HopscotchWindow openSubject: (classBrowser UI new ClassSubject onModel: klass)

#+end_example

